### ISSUE TITLE
SVD via GEVD

### ISSUE THREAD

**Issue by serjl** [ndvanforeest/fit_ellipse#2]
Hello,
Can you please comment why the "largest solution" of the eigenvalue problem  $\frac{1}{\lambda} a = S^{-1} C a$, namely  the eigenvector corresponding to the largest eigenvalue $1/\lambda$ is given by the left singular vector corresponding to the largest singular value:  
U, s, V = svd(np.dot(inv(S), C))
return U[:, 0]

As far as I see there is no direct connection between these decompositions in THIS case, since $S^{-1} C$ is not normal in general.
Thank you in advance.

**Comment by ndvanforeest** [comment]
Hi,

That is in the documentation of svd, isn’t it?

**Comment by serjl** [comment]
Yes, I am asking about the pdf file on the way of the solution and the actual usage in the python code.
The two things seem different. At least, I understand the solution from pdf and can not get to the point why python code gives the right solution.

**Comment by ndvanforeest** [comment]
We want lambda minimal, so we want 1/lambda maximal.

**Comment by serjl** [comment]
Probably I explained myself badly. I ask why the eigenvector $v_max$ corresponding to the maximal eigenvalue $1/lambda_min$ of the matrix $S^{-1} C$ equals to the singular vector U[:, 0] corresponding to the largest singular value of the $U, s, V = svd(np.dot(inv(S), C))$.
In general, there are no any reasonable relation between this.

**Comment by ndvanforeest** [comment]
Sorry, but I don’t understand your problem. The docs of svd say that the singular values are non increasing. Then the U contains the eigenvectors associated with these singular values. And then we want the left most such eigenvector.

**Comment by serjl** [comment]
My problem is that SVD  of a matrix $A$ does not  give its egenvalues/vectors. It gives the singular values/vectors, which are the eigenvalues/vectors of $\sqrt(AA^*)$. Except for positive semi-definite normal matrices, the eigenvalue decomposition and SVD of $A$  differ.
On the other hand, the docs of SVD shows that the answer to the ellipse fit problem comes from the eigenvalue decomposition of the matrix $S^{-1} C$. This matrix is not  positive semi-definite normal in general.  Actually one needs that $S^{-1} C$ 
be positive semi-definite unitarily diagonalized (using a basis of eigenvectors), which is not in general.
Nevertheless you use SVD in the python code to solve the problem. My question is therefor, why it is correct.

**Comment by ndvanforeest** [comment]
I see now :-)  I'll update the pdf. This symmetry must hold because the
Lagrangian is symmetric. In my derivation I put the a at the right, but you
can just as well write a at the left. Hence, a must also be an eigenvector
(save transposition) of C S^{-1}, and C is symmetric. You agree?

**Comment by serjl** [comment]
"Lagrangian is symmetric" - yes it is just a real valued function, so what?
From what you  wrote i don't see how it works. From the left you can put only a^t,
so (a^t)C S^{-1} = 1/lambda*(a^t). It has nothing to do with C S^{-1}(a) = 1/lambda*(a).
But I have even worse question: why $S^{-1} C$ has real eigenvalues at all. This is 6x6 matrix that can have in general only complex eigenvalues.

**Comment by serjl** [comment]
"Lagrangian is symmetric" - yes it is just a real valued function, so what?
From what you wrote i don't see how it works. From the left you can put only a^t (row vector once u began with a column vector a), so (a^t)C S^{-1} = 1/lambda*(a^t). It has nothing to do with C S^{-1}(a) = 1/lambda*(a).
But I have even worse question: why $S^{-1} C$ has real eigenvalues at all. This is 6x6 matrix that can have in general only complex eigenvalues.

**Comment by ndvanforeest** [comment]
Sent from my iPad

> On 17 Aug 2020, at 22:03, serjl <notifications@github.com> wrote:
> 
> ﻿
> "Lagrangian is symmetric" - yes it is just a real valued function, so what?
> From what you wrote i don't see how it works. From the left you can put only a^t,
> so (a^t)C S^{-1} = 1/lambda*(a^t). It has nothing to do with C S^{-1}(a) = 1/lambda*(a).
> But I have even worse question: why $S^{-1} C$ has real eigenvalues at all. This is 6x6 matrix that can have in general only complex eigenvalues.
> 

Sure, but in this case the number phi is positive, and real. Moreover, aSa is positive and real because S is the product of D with itself. Hence, lambda is real and positive. 

Have you had a look in golub and van loon? Perhaps you can find the rest of the answer there.

**Comment by serjl** [comment]
Yes i read their paper, and their solution says: solve generalized eigenvalue problem (GEP)  $S a = \lambda C a$, which is indeed solvable and has 6 real solutions because S and C are symmetric. Then the constrain (a^t)C a = 1 dictates to take $\lambda_min$.
The standard solution of GEP IS NOT  given by SVD of  $S^{-1} C$. So if you have a proof of the correctness of your python formula, it would help a lot. In any case thank you for trying to clarify.

**Comment by serjl** [comment]
Yes i looked in this book too and many others. Everywhere the solution of generalized eigenvalue problem (in our case even Symmetric-Definite Problem  8.7.1-8.7.2 in golub and van loon )  $S a = \lambda C a$, which is indeed solvable and has 6 real solutions because S and C are symmetric, IS NOT  given by SVD of  $S^{-1} C$, but by the simultaneous diagonalization of S and C.  So if you have a proof of the correctness of your python formula, it would help a lot. In any case thank you for trying to clarify.

**Comment by ndvanforeest** [comment]
Thanks. I don’t recall why I used svd, it’s 14 years ago that I played with it. Would you be so kind to replace the svd by another method to find the smallest eigenvalue? 

Might it be that in the paper of fitzsimmons they use svd?

**Comment by serjl** [comment]
In the paper of fitzsimmons - they get to $S a = \lambda C a$ and say that this problem is readily solvable without mentioning the method. In an y case, it is not that difficult to solve by  the simultaneous diagonalization of S and C, which  can be done even with svd (should be applied twice properly).  I will try to do it at the following weekend.

**Comment by ndvanforeest** [comment]
Perhaps you like the explanation in Christopher bishops book, pattern regocnition and machine learning, section 12.1 on principal component analysis. The book is free for download.
