### ISSUE TITLE
sign error in rotation matrix [run_fit_ellipse.py]

### ISSUE THREAD

**Issue by mcarlstedt** [ndvanforeest/fit_ellipse#4]
file: run_fit_ellipse.py
line: 19

There is a sign error in the example file: run_fit_ellipse.py.
The rotation matrix hat to be a skew-symmetric matrix, not a symmetric.

R =[[ cos(theta) ,  sin(theta)],
      [- sin(theta) ,  cos(theta)]]

current:  return np.matrix([[ct, st], [st, ct]])
new:      return np.matrix([[ct, st], [-st, ct]])

**Comment by ndvanforeest** [comment]
Sure. Thanks.
