### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by chelsell** [ndvanforeest/fit_ellipse#5]
Hi, thanks for writing a very useful bit of code! I just want to draw your attention to what looks like a version mismatch between the documentation and the current code. It's very minor and didn't cause me any trouble, but some user out there might one day become confused by it. Basically in the doc example you call `a = fitEllipse(x,y)`, but there is no function by that name! Based on what comes after, it looks like `fitEllipse` is an old name for the private function `__fit_ellipse`. By my lights the documentation should say this:

```
a = fit_ellipse(x,y)
major_axis, minor_axis = a[0], a[1]
center = (a[2],a[3])
phi = a[4]
```

Cheers!

**Comment by ndvanforeest** [comment]
Thanks for pointing it out. I updated the docs.
