### ISSUE TITLE
Corner cases

### ISSUE THREAD

**Issue by kif** [ndvanforeest/fit_ellipse#7]
Hi,
I got inspired by your code a while ago and found some corner cases, which result apparently depend on the version of numpy ...
https://github.com/silx-kit/pyFAI/blob/master/doc/source/usage/tutorial/Ellipse/ellipse.ipynb
The cell #7 no more works on recent numpy.
Are you interested in debugging those issues ?
Thanks,

Jérôme

**Comment by ndvanforeest** [comment]
Hi Jerome,

I just included a link to a module in scikit for this problem. Hopefully you can use that instead.
