### ISSUE TITLE
negative value when finding major minor axis

### ISSUE THREAD

**Issue by mgkumar138** [ndvanforeest/fit_ellipse#8]
when finding the major and minor axis length using a, **down1** variable in ellipse_axis_length gives a negative value. When computing res1 with a square root(up/down1) this gives a Nan value since down1 is negative while up is positive. Is there a workaround from this?

**Comment by dlamm1997** [comment]
@mgkumar138  Have you made any progress on this? I am troubleshooting the same issue at the moment.

**Comment by ndvanforeest** [comment]
Sorry, no, i don’t have much time right now, but if you have a repair, please file a pr.

**Comment by ndvanforeest** [comment]
Please check out the module on scikit for this problem.
