### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by Pullusb** [ndvanforeest/fit_ellipse#9]
Hi @ndvanforeest ! (and Happy new year ^^)
Thank you for sharing this with the world.
I wondered what's the code license ? Can it be reused anywhere ?

**Comment by ndvanforeest** [comment]
Hi,

Nice to hear you find it useful. There is no license, but also no warranty 😀 

Happy new year to you too.

Nicky

**Comment by cosinekitty** [comment]
@ndvanforeest You might consider adding an MIT license. It pretty much says what you just did: (a) You can do what you want, (b) It's not my fault if you don't like the result.

**Comment by ndvanforeest** [comment]
Thanks. I ll do that, and give some thought to the other open issues too.
